dist: bionic
language: node_js
node_js:
    - "10"
    - "12"
services:
  - docker
env:
  global:
    - DEV_BRANCH=dev
    - RELEASE_BRANCH=main
    - POST_RELEASE_BRANCH=main
    - RELEASE_MESSAGE=release
cache:
    npm: true
    directories:
        - "node_modules"
before_script:
    - . ./travis/node-functions.sh && log_env_variables
    - VERSION="$(node_load_version)"
script:
    - npm run build
jobs:
  include:
    - stage: test
      mame: lint
      script: npm run lint
    - mame: e2e tests
    - stage: test
      name: docker test build
      script: /bin/bash travis/docker-functions.sh docker_build $VERSION
    - stage: publish
      name: docker publish alpha
      script: /bin/bash travis/docker-functions.sh docker_build $VERSION publish
      if: branch = env(DEV_BRANCH) AND type = push
    - stage: release
      name: docker publish release
      script: /bin/bash travis/docker-functions.sh docker_build $VERSION release
      if: branch = env(RELEASE_BRANCH) AND type = api AND commit_message = env(RELEASE_MESSAGE)
    - stage: post release
      name: tag and version upgrade
      script: /bin/bash travis/node-functions.sh node_post_release
      if: branch = env(RELEASE_BRANCH) AND type = api AND commit_message = env(RELEASE_MESSAGE)
