dist: bionic
language: node_js
node_js:
    - "10"
    - "12"
services:
  - docker
cache:
    npm: true
    directories:
        - "node_modules"
script:
    - npm run build
jobs:
  include:
    - stage: test
      name: lint tests
      script: npm run lint
      os: linux

    - stage: alpha
      name: publish alpha docker
      script: /bin/sh travis/docker.sh
      if: branch = env(MAIN_BRANCH) AND type != pull_request AND (commit_message != release OR env(RELEASE_BRANCH) != env(MAIN_BRANCH))
      os: linux

    - stage: release
      name: release docker
      script: /bin/sh travis/docker.sh
      if: branch = env(RELEASE_BRANCH) AND type != pull_request AND (commit_message = release OR env(RELEASE_BRANCH) != env(MAIN_BRANCH))
      os: linux

    - name: release artifacts, tag and update version
      script: /bin/sh travis/release.sh
      if: branch = env(RELEASE_BRANCH) AND type != pull_request AND (commit_message = release OR env(RELEASE_BRANCH) != env(MAIN_BRANCH))
      os: linux